[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip", "pkg-config", "libudev-zero"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --omit=optional || npm install --legacy-peer-deps --no-optional --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

