[phases.setup]
nixPkgs = ["nodejs_22", "python3", "gcc", "gnumake", "pkg-config", "systemdMinimal"]

[phases.install]
cmds = ["npm install --legacy-peer-deps || npm install --legacy-peer-deps --no-optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

